name: Windows Builds

on:
  push

jobs:
  windows_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Debug
      shell: bash
      run: |
        rm -Rf cmake-build
        cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build cmake-build --target AudioPerformanceTest
        cmake --build cmake-build --target AudioPluginHost
        cmake --build cmake-build --target BinaryBuilder
        cmake --build cmake-build --target DemoRunner
        cmake --build cmake-build --target NetworkGraphicsDemo
        cmake --build cmake-build --target Projucer
        cmake --build cmake-build --target UnitTestRunner

    - name: Unit Tests Debug
      shell: bash
      run: cmake-build/examples/DemoRunner/DemoRunner_artefacts/Debug/UnitTestRunner.exe

    - name: Build Release
      shell: bash
      run: |
        rm -Rf cmake-build
        cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake-build --target AudioPerformanceTest
        cmake --build cmake-build --target AudioPluginHost
        cmake --build cmake-build --target BinaryBuilder
        cmake --build cmake-build --target DemoRunner
        cmake --build cmake-build --target NetworkGraphicsDemo
        cmake --build cmake-build --target Projucer
        cmake --build cmake-build --target UnitTestRunner

    - name: Unit Tests Release
      shell: bash
      run: cmake-build/examples/DemoRunner/DemoRunner_artefacts/Release/UnitTestRunner.exe
